# Service Name and Port
server:
  port: 8002
  servlet:
    session:
      timeout: 30m # Session hết hạn sau 30 phút

spring:
  application:
    name: AUTH-SERVICE

  # MySQL Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/doanii_users?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 712004dkt

  # JPA/Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  data:
    redis:
      host: localhost
      port: 6379
  session:
    store-type: redis
    redis:
      namespace: doanii:session

# Eureka Discovery Client Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: bXktc2VjcmV0LWtleS1mb3ItZG9hbi1paS1wcm9qZWN0LW11c3QtYmUtbG9uZy1hbmQtY29tcGxleA==
  expiration:
    ms: 3600000
